spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000