spring:
  application:
    name: user-service

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:users}
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${DATA_REDIS_HOST:redis}
      port: ${DATA_REDIS_PORT:6379}
      timeout: ${DATA_REDIS_TIMEOUT:2000}

server:
  port: ${SERVER_PORT:8081}
logging:
  level:
    root: INFO
    ru.sg: DEBUG
