spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/${CONFIG_RESOURCES_PATH}/config/eureka
            - file:/${CONFIG_RESOURCES_PATH}/config/license
            - file:/${CONFIG_RESOURCES_PATH}/config/gateway
            - file:/${CONFIG_RESOURCES_PATH}/config/organization