server:
  port: 8070
  waitTimeInMsWhenSyncEmpty: 5
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/