spring:
  application:
    name: gateway-service
  profiles:
    active: dev

server:
  port: 9000
logging:
  level:
    root: info
    ru.sg: DEBUG

services:
  user-services:
    user-service:
      url: http://user-service:8080
      path: /api/v1/users/**
    order-service:
      url: http://order-service:8080
      path: /api/v1/orders/**
    onto-service:
      url: http://onto-service:8080
      path: /api/v1/onto/**