spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/microservices
          jwk-set-uri: http://localhost:9080/realms/microservices/protocol/openid-connect/certs

  data:
    redis:
      host: localhost
      port: 6379